from django.urls import path
from apps.core.views import home, pages

urlpatterns = [
    path("", home.HomeView.as_view(), name="home"),
    path("features/", pages.FeaturesView.as_view(), name="features"),
    path("pricing/", pages.PricingView.as_view(), name="pricing"),
    path("about/", pages.AboutView.as_view(), name="about"),
    path("contact/", pages.ContactView.as_view(), name="contact"),
    path("faq/", pages.FAQView.as_view(), name="faq"),
    path("privacy/", pages.PrivacyView.as_view(), name="privacy"),
    path("terms/", pages.TermsView.as_view(), name="terms"),
    path("url-scanner/", pages.UrlScanView.as_view(), name="url_scan"),
    path("url-scanner/<uuid:scan_id>/", pages.ScanDetailView.as_view(), name="scan_detail"),
    path("file/", pages.FileScanView.as_view(), name="file_scan"),
    path("email-scanner/", pages.EmailScanView.as_view(), name="email_scan"),
    path("ip-scanner/", pages.IPScanView.as_view(), name="ip_scan"),
    path("domain-scanner/", pages.DomainScanView.as_view(), name="domain_scan"),
    path("phishing/", pages.PhishingAnalysisView.as_view(), name="phishing_analysis"),
    path("phishing/header-analyzer/", pages.EmailHeaderAnalyzerView.as_view(), name="email_header_analyzer"),
    path("phishing/health-checker/", pages.EmailHealthCheckerView.as_view(), name="email_health_checker"),
    path("phishing/suspicious-blocker/", pages.SuspiciousEmailBlockerView.as_view(), name="suspicious_email_blocker"),
    path("sandbox/", pages.SandboxView.as_view(), name="sandbox"),
    path("threat-intel/", pages.ThreatIntelView.as_view(), name="threat_intel"),
    path("vulnerability-scanner/", pages.VulnScanView.as_view(), name="vuln_scan"),
    path("ssl-checker/", pages.SSLCheckerView.as_view(), name="ssl_checker"),
    path("dns-lookup/", pages.DNSLookupView.as_view(), name="dns_lookup"),
    path("whois-lookup/", pages.WHOISLookupView.as_view(), name="whois_lookup"),
    path("dark-web/", pages.DarkWebView.as_view(), name="dark_web"),
    path("breach-check/", pages.BreachCheckView.as_view(), name="breach_check"),
    path("scan-history/", pages.ScanHistoryView.as_view(), name="scan_history"),
    path("saved-reports/", pages.SavedReportsView.as_view(), name="saved_reports"),
    path("settings/", pages.SettingsView.as_view(), name="settings"),
    path("api-settings/", pages.ApiSettingsView.as_view(), name="api_settings"),
    path("api-docs/", pages.ApiDocsView.as_view(), name="api_docs"),
    path("help/", pages.HelpView.as_view(), name="help"),
    path("docs/", pages.DocsView.as_view(), name="docs"),
    path("blog/", pages.BlogView.as_view(), name="blog"),
    path("tools/", pages.FeaturesView.as_view(), name="tools"),
]
