# Generated by Django 5.2.15 on 2026-07-04 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeaderScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_header', models.TextField(verbose_name='raw header')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='scanned at')),
                ('status', models.CharField(default='complete', max_length=50, verbose_name='status')),
                ('from_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='from email')),
                ('sender_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='sender IP')),
                ('spf_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='SPF result')),
                ('dkim_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='DKIM result')),
                ('dmarc_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='DMARC result')),
                ('spoofing_detected', models.BooleanField(default=False, verbose_name='spoofing detected')),
                ('threat_score', models.IntegerField(default=0, verbose_name='threat score')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='is malicious')),
                ('hops', models.JSONField(blank=True, null=True, verbose_name='hops')),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='analysis result')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_header_scans', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email header scan',
                'verbose_name_plural': 'email header scans',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='domain')),
                ('mx_records', models.JSONField(blank=True, default=list, verbose_name='MX records')),
                ('spf_result', models.JSONField(blank=True, default=dict, verbose_name='SPF result')),
                ('dkim_results', models.JSONField(blank=True, default=list, verbose_name='DKIM results')),
                ('dmarc_result', models.JSONField(blank=True, default=dict, verbose_name='DMARC result')),
                ('blacklist_results', models.JSONField(blank=True, default=list, verbose_name='blacklist results')),
                ('ptr_result', models.JSONField(blank=True, default=dict, verbose_name='PTR result')),
                ('smtp_banner', models.TextField(blank=True, verbose_name='SMTP banner')),
                ('health_score', models.PositiveSmallIntegerField(default=0, verbose_name='health score')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='score breakdown')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_health_checks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email health check',
                'verbose_name_plural': 'email health checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousEmailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, max_length=500, verbose_name='subject')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='sender email')),
                ('sender_domain', models.CharField(blank=True, max_length=255, verbose_name='sender domain')),
                ('email_body', models.TextField(blank=True, verbose_name='email body')),
                ('attachments_info', models.JSONField(blank=True, default=list, verbose_name='attachments info')),
                ('links_found', models.JSONField(blank=True, default=list, verbose_name='links found')),
                ('phishing_indicators', models.JSONField(blank=True, default=list, verbose_name='phishing indicators')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='risk score')),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], default='clean', max_length=20, verbose_name='verdict')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_email_reports', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'suspicious email report',
                'verbose_name_plural': 'suspicious email reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
