# Generated by Django 5.2.15 on 2026-07-07 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainHealthScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='domain')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='scanned at')),
                ('status', models.CharField(default='complete', max_length=50, verbose_name='status')),
                ('mx_records', models.JSONField(blank=True, null=True, verbose_name='MX records')),
                ('spf_record', models.TextField(blank=True, null=True, verbose_name='SPF record')),
                ('dkim_found', models.BooleanField(default=False, verbose_name='DKIM found')),
                ('dmarc_record', models.TextField(blank=True, null=True, verbose_name='DMARC record')),
                ('blacklist_hits', models.IntegerField(default=0, verbose_name='blacklist hits')),
                ('blacklists_checked', models.IntegerField(default=0, verbose_name='blacklists checked')),
                ('health_score', models.IntegerField(default=0, verbose_name='health score')),
                ('health_grade', models.CharField(blank=True, max_length=2, null=True, verbose_name='health grade')),
                ('issues', models.JSONField(blank=True, null=True, verbose_name='issues')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_health_scans', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'domain health scan',
                'verbose_name_plural': 'domain health scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
