# Generated by Django 5.2.15 on 2026-07-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_domainhealthscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_body', models.TextField(verbose_name='email body')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='scanned at')),
                ('status', models.CharField(default='complete', max_length=50, verbose_name='status')),
                ('phishing_score', models.IntegerField(default=0, verbose_name='phishing score')),
                ('verdict', models.CharField(blank=True, max_length=100, null=True, verbose_name='verdict')),
                ('is_phishing', models.BooleanField(default=False, verbose_name='is phishing')),
                ('indicators', models.JSONField(blank=True, null=True, verbose_name='indicators')),
                ('urls_found', models.JSONField(blank=True, null=True, verbose_name='URLs found')),
                ('keywords_found', models.JSONField(blank=True, null=True, verbose_name='keywords found')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_content_scans', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email content scan',
                'verbose_name_plural': 'email content scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
