# Generated by Django 5.2.15 on 2026-07-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('stdin_input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('memory_mb', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sandbox Execution',
                'verbose_name_plural': 'Sandbox Executions',
                'ordering': ['-executed_at'],
            },
        ),
    ]
