# Generated by Django 6.0.6 on 2026-06-17 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeaderScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_headers', models.TextField(verbose_name='raw headers')),
                ('parsed_json', models.JSONField(blank=True, default=dict, verbose_name='parsed headers')),
                ('sender_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='sender IP')),
                ('spf_result', models.CharField(blank=True, max_length=20, verbose_name='SPF result')),
                ('dkim_result', models.CharField(blank=True, max_length=20, verbose_name='DKIM result')),
                ('dmarc_result', models.CharField(blank=True, max_length=20, verbose_name='DMARC result')),
                ('routing_hops', models.JSONField(blank=True, default=list, verbose_name='routing hops')),
                ('threat_score', models.PositiveSmallIntegerField(default=0, verbose_name='threat score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_scans', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email header scan',
                'verbose_name_plural': 'email header scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
