# Generated by Django 6.0.6 on 2026-06-17 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='domain')),
                ('mx_records', models.JSONField(blank=True, default=list, verbose_name='MX records')),
                ('spf_result', models.JSONField(blank=True, default=dict, verbose_name='SPF result')),
                ('dkim_results', models.JSONField(blank=True, default=list, verbose_name='DKIM results')),
                ('dmarc_result', models.JSONField(blank=True, default=dict, verbose_name='DMARC result')),
                ('blacklist_results', models.JSONField(blank=True, default=list, verbose_name='blacklist results')),
                ('ptr_result', models.JSONField(blank=True, default=dict, verbose_name='PTR result')),
                ('smtp_banner', models.TextField(blank=True, verbose_name='SMTP banner')),
                ('health_score', models.PositiveSmallIntegerField(default=0, verbose_name='health score')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='score breakdown')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_health_checks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email health check',
                'verbose_name_plural': 'email health checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
