# Generated by Django 6.0.6 on 2026-06-17 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_emailhealthcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousEmailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, max_length=500, verbose_name='subject')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='sender email')),
                ('sender_domain', models.CharField(blank=True, max_length=255, verbose_name='sender domain')),
                ('email_body', models.TextField(blank=True, verbose_name='email body')),
                ('attachments_info', models.JSONField(blank=True, default=list, verbose_name='attachments info')),
                ('links_found', models.JSONField(blank=True, default=list, verbose_name='links found')),
                ('phishing_indicators', models.JSONField(blank=True, default=list, verbose_name='phishing indicators')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='risk score')),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], default='clean', max_length=20, verbose_name='verdict')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_email_reports', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'suspicious email report',
                'verbose_name_plural': 'suspicious email reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
