# Generated by Django 5.2.15 on 2026-07-07 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('final_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('server_header', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.CharField(blank=True, max_length=200, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('redirect_count', models.IntegerField(default=0)),
                ('load_time_ms', models.FloatField(blank=True, null=True)),
                ('dom_nodes', models.IntegerField(default=0)),
                ('images', models.IntegerField(default=0)),
                ('links', models.IntegerField(default=0)),
                ('css_files', models.IntegerField(default=0)),
                ('scripts_removed', models.IntegerField(default=0)),
                ('inline_scripts_removed', models.IntegerField(default=0)),
                ('external_scripts_removed', models.IntegerField(default=0)),
                ('forms_removed', models.IntegerField(default=0)),
                ('iframes_removed', models.IntegerField(default=0)),
                ('objects_removed', models.IntegerField(default=0)),
                ('event_handlers_removed', models.IntegerField(default=0)),
                ('dangerous_urls_removed', models.IntegerField(default=0)),
                ('meta_refresh_removed', models.IntegerField(default=0)),
                ('mixed_content_found', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('sanitized_html', models.TextField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('redirect_chain', models.JSONField(blank=True, default=list, null=True)),
                ('removed_elements', models.JSONField(blank=True, default=list, null=True)),
                ('security_headers', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Isolation Scan',
                'verbose_name_plural': 'Isolation Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
