# Generated by Django 5.2.15 on 2026-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('asset_type', models.CharField(max_length=50)),
                ('risk_score', models.IntegerField()),
                ('breach_count', models.IntegerField(default=0)),
                ('total_records_exposed', models.BigIntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'scan result',
                'verbose_name_plural': 'scan results',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
