# Generated by Django 5.2.15 on 2026-07-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_hash_md5', models.CharField(blank=True, max_length=32, null=True)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('scanning', 'Scanning'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_malicious', models.BooleanField(blank=True, null=True)),
                ('threat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('threat_score', models.IntegerField(blank=True, null=True)),
                ('vendors_total', models.IntegerField(default=0)),
                ('vendors_flagged', models.IntegerField(default=0)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Scan',
                'verbose_name_plural': 'File Scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
