# Generated by Django 5.2.15 on 2026-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filescanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescan',
            name='scan_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
